### ISSUE TITLE
키워드

### ISSUE THREAD

**Issue by oeeen** [oeeen/TIL#12]
- Future
- Batch Job 관련 (ScheduledTaskRegistrar 에서 Task들이 어떻게 실행되는가)
- Async stack trace
- Redis
- Index
- ~~L3DSR~~
- ~~Write Concern~~

**Comment by oeeen** [comment]
- ~~ARP~~
- ~~OSPF~~
- ~~BGP~~
- ~~Spanning Tree Protocol~~
- ~~HSRP, VRRP~~
- IP in IP tunneling
- ~~IPSec, IKE~~
- Spark
- Kafka
- ~~SNI~~
- ~~gradle multi module~~
- terraform(ncp) - [https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest](https://registry.terraform.io/providers/NaverCloudPlatform/ncloud/latest)
- ~~직렬화~~
- logger
- apache airflow
- apache druid
- properties 적용 순서
- jpa deleteBy~~ transaction, entitymanager
- transactional, nativeQuery, Exception
- https://aozturk.medium.com/how-to-handle-uncaught-exceptions-in-java-abf819347906

**Comment by andole98** [comment]
와 이건 하나도 모르겠다ㅋㅋㅋㅋㅋㅋ 공부해서 알려줘
