### ISSUE TITLE
이벤트 소싱 관련 자료 공유합니다~!

### ISSUE THREAD

**Issue by hyunssooo** [oeeen/TIL#3]
https://youtu.be/TDhknOIYvw4 

스프링캠프에서 이규원님이 발표 하신 영상입니다! 

d2에서 발표 하신 영상도 있습니다 :) 

https://youtu.be/Yd7TXUdcaUQ

**Comment by oeeen** [comment]
👍

**Comment by oeeen** [comment]
close 할게요~
